### ISSUE TITLE
Sunday Schedule not complete

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#29]
We are missing everything after the Workshops on Sunday. Nothing is listed in the google doc.

**Comment by SwinginSteps** [comment]
It's now complete, feel free to update the website whenever it feels comfortable :-)

**Comment by SwinginSteps** [comment]
at the time of checking (27.07 @12:25 am) this didn't seem completed ...

**Comment by OvidiuS** [comment]
@SwinginSteps Ye gods man, don't you have anything better to do at this time of the night? :))) I didn't assign this to you yet. The changes / fixes are local only.  Will let you know when I update the database to the staging server.
