### ISSUE TITLE
The Plan: no marketplace content.

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#30]
There isn't anything to say about the marketplace on the "Plan" page. It's supposed to be a section that gets linked to from "The Plan > Marketplace" item on the homepage.

**Comment by SwinginSteps** [comment]
Indeed. wip

**Comment by SwinginSteps** [comment]
a first draft is available, feel free to check it out and give feedback :-)

**Comment by SwinginSteps** [comment]
Content should be finished. Exista un text introductiv si apoi o listare a partenerilor confirmati momentan. Vrem sa adaugam o mica descriere la fiecare dintre ei, dar inca nu am primit nimica scris din partea lor, for now, it's just going to be a plain list. To be changed later.
