### ISSUE TITLE
FAQs page -  create page template

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#31]
The FAQs page is an attempt on Ovi's part to find a meaningful and helpful structure for the content provided by Andrei. The items on the content google doc's "The Plan" tab look better as FAQs, in Ovi's opinion. This page should have the same outside template as the rest of the inner pages, and an FAQ matrix field inside of it.

**Comment by SwinginSteps** [comment]
Looks good. Will think about more content!
