### ISSUE TITLE
Highlight BIOs

### ISSUE THREAD

**Issue by SwinginSteps** [OvidiuS/Citadel-Swing-Website#37]
Highlight the Pro BIOs in an intuitive way, so the user knows he CAN click on them.
Change mouse pointer to regular Hand pointer (used in links) ?

**Comment by OvidiuS** [comment]
agreed on using hand pointer. will do.

**Comment by SwinginSteps** [comment]
Will that be all the highlighting you'll do sau te gandesti si la ceva color change on hover?

**Comment by SwinginSteps** [comment]
Highlighting with just a mouse pointer change is practically invisible ... we need something more.
Here are a few ideas:
 - change background color to a lighter pink color (something like a white-ish overlay)
 - overlay the whole box with another layer and in the middle have a "clikc for more details" text - http://ryun.github.io/HCaptions/ Fade effect (the second one) would be awesomezor
