### ISSUE TITLE
Eventbrite Mobile App

### ISSUE THREAD

**Issue by SwinginSteps** [OvidiuS/Citadel-Swing-Website#38]
It is mentioned that people can bring their Tickets on mobile, with the eventbrite mobile app.
This is mentioned under:
http://csdev.dvsdev.xyz/schedule Warmup & Gathering
http://csdev.dvsdev.xyz/faqs Registration & Checkin
I'm not aware that participants have access to a eventbrite mobile app.
I think they can only download the ticket in digital form and show it using their mobile devices. Are you sure they have access to an eventbrite mobile app?

**Comment by SwinginSteps** [comment]
There's a Mobile App for organizers, that i know. It can be used to Checkin the registered ppl. ... but that's different, isn't it? :)

**Comment by OvidiuS** [comment]
This is the mobile app i was talking about: https://www.eventbrite.com/eventbriteapp/
It's also used to display the ticket in digital form, so that we can check people in.
