### ISSUE TITLE
home: add links from "The Plan" section to "The Plan" page.

### ISSUE THREAD

**Issue by SwinginSteps** [OvidiuS/Citadel-Swing-Website#40]
There should be links on the Homepage under The Plan, pointing to each item from The Plan page (http://csdev.dvsdev.xyz/the-plan)
Initial Suggestion was to add a small line like "details ..." or "more ...", but the box itself can also be a link as long as it's changing the mouse pointer

**Comment by OvidiuS** [comment]
still missing content for "The Plan" page. Will add the links once we have that page up and running. The way it looks now we might want to launch without it, just the get the bios, schedule and FAQs pages out already.

**Comment by SwinginSteps** [comment]
should be more feasible now, right?
