### ISSUE TITLE
Home link sometimes just scrolls up

### ISSUE THREAD

**Issue by SwinginSteps** [OvidiuS/Citadel-Swing-Website#56]
So when i'm in any of the other pages that are not home and i'm scrolled down, then click the home button from the small "always on top" menu, it will just scroll me back up on the same page.
If this intentional?
If so, it's a little confusing, because people would generally expect it to get you back to the homepage.

**Comment by OvidiuS** [comment]
@SwinginSteps good catch, I found this bug myself two days ago and I thought I had filed it in the  system, but I didn't. Will fix.

**Comment by OvidiuS** [comment]
@SwinginSteps I can't reproduce this bug anymore, can you remember on which pages you saw this behavior? I checked all the pages and couldn't find it.

**Comment by SwinginSteps** [comment]
go to schedule, scroll down, hit home
