### ISSUE TITLE
Schedule: First Workshops details - dummy info

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#57]
We need to remove the dummy descriptions or create actual ones. I vote remove.

**Comment by OvidiuS** [comment]
For the record, I'm talking about the descriptions of the Saturday Workshops at 10:00-11:00 AM.

**Comment by OvidiuS** [comment]
Decided on my own to remove the dummy descriptions, as I got no response.

**Comment by SwinginSteps** [comment]
perfect
