### ISSUE TITLE
About Timisoara first version

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#63]
create the page, add the text from Alexandra, add some images about Timisoara.

**Comment by SwinginSteps** [comment]
Some typos:
1st paragraph, last sentence: 
 - we are looking forward to welcoming you there in September.
 - we are looking forward to welcoming you here in September.

3rd paragraph, 1st sentence:
 - The opera and the entrance ticket only cost 5 euros.
The Opera only costs 5 euros? i would buy the Opera right away! Seems like something got lost through editing

Everything else looks delicious! I love the pictures :)
